apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo/system/namespaces/
    repoURL: 'https://github.com/scuffe82/helios'
    targetRevision: HEAD
  project: default