apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '21.0.3'
    chart: nginx
    helm:
      valueFiles:
      - https://github.com/scuffe82/helios/blob/main/argo/remote/nginx/nginx-values.yaml
#  - repoURL: 'https://github.com/scuffe82/helios.git'
#    targetRevision: HEAD
#    ref: values
  destination:
    namespace: remote
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true