apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webtop
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo/remote/webtop/
    repoURL: 'https://github.com/scuffe82/helios'
    targetRevision: HEAD
  project: default