---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: security
spec:
  encryptedData:
    api-token: AgBTlmZPibbTGYPoDnrsJhdJ3XfPlzZ0dBqT5mfsXS6/jnGnlKBupbAWlJ85HWzBPp0dnO23Rkb3EGxS51zvO40g0kP/yVL4fY1xNjqD/L5f129Xm6Tn2jS+BPSD/Wp73n21HCm8Mv5qWZuGfuF5Y9OzU2q6s4u3E5B5RwmjXVSzYOCP1z0CbkwoQw44DoXlnhq9U73srg+YSspgCD7diBfQ/3CwTHtfF5BhScexM0nPS+9W5VSE9nz1Xh+TBnapJf1YIAW8zRU0QnVENegGfo8pMa6EzvvNLjr7ziHEEyockqASyzqv8OQiL6bgsIRvXIe42EXLBRBfV7JQo8w1n7rZGc1TKptA6xR/5GWA7/04UWc6Ziz58+nnDUiQ4UwViTjWASDGfp+0xzrKyCvrVfByWcmBANrZRHDhC43y99wMPruMxVR5xz5G3Xm4jZA75i/gG6YdYMX5qx80yUntv2zzLR7QPWRNVn1LC0tQ9ipaUflLdjqHgTvj4Tfe4iO/TMJHs8SZcFy6jMmpdkwXhBQ6PPEMg3SiQwW/I1aip/udlJCZviU6KEvggUZzJQA6wgBPddGVt8RjSHFW3E14Lb9AbXgmqBxITj7OvXue8KFHE5x5apIc/BfgraIf3RxEOspnVoRqIIhHHOegWTrN556I5HVgf9Ni9wJmirriBh1By5F1woAIClXaFvRig9yFa8qEZw4KkIc+LqTS+wTumIzoy1AaKpgkPsYoGU7PXyq9riZNXQ9ewUSp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: security
