---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: security
spec:
  encryptedData:
    api-token: AgAd5D0LkdKpLhSesA7LD4loKrZcD/Z+dHwkWfejNmd2rdnyHVMrnAlmoY85S6enH3rUT3ohAPFMRQIYHC3oz2b4EpPyh/WFBVtMA978QXaixP4zh5oUQ+eYdp7OFz5kixMIIbfdBMqg/9kTBtB4SPc3oP3unaqcvy/GvR7vQVNI2633mirRKfdpyqOCLxAWGlDWnuMv6zqyY/2wm+gydU7UU7ZCBoXR30bNmSjZOC+hNjhYbwFBa2Ox+yE7GuNpMgsamxIGJne79HjFx1UX0ni5jHVCmowY3RjM6ROB1EW8pHXgjPyy4pn+ZwgGa2iBGXM3E36kRIh64WuKUeQ7uHmrPz5ROVLTUXU++JLLkYvv29iLf5omv1uvWqLcnp5GpztkvM83FlLsI1nqh4Ib40AjvYB8CO+toWHU4wXzzSSyK9K6hhq7sYPeJm8RZnazlP6R6xgu3XQgHNGsnNwEPjE1hF3yL3BD6+fDebB0FeHOxyCf/MdVWm7griVMJhGbRdeb84EljAm64JT26Ic7EP7vTXuDxBk5puCkDoivRMntlYtALm5KKALnCfj08FV0hX2de0c3FEi2P/nljaX7eOvaWQwZoGiXEQRRndEwTbCwYFxhVoovqM+3sFlujlhU3V+s3RiWT1gUdvB9bHB7SK0yDRF66bk0cnvkjnHzmNahghnflrDTzssHqhQaD8Bp9EIQvtx0D3FPzEqZ9rvbeD63bE5DGqXWUtVBo1/o8Z+V5zcBNSwCX/Lz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: security
