---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
  labels:
    type: sonarr-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.10:3260
     iqn: iqn.2000-01.com.synology:crypteia.sonarr
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: sonarr-config
  storageClassName: ""
  volumeName: sonarr-config
