apiVersion: v1
kind: Secret
metadata:
  name: spenceops-helios-public
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/scuffe82/helios.git