apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-cluster
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: cluster/
    repoURL: 'https://github.com/scuffe82/helios.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false