---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget-config
  labels:
    type: nzbget-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.10:3260
     iqn: iqn.2000-01.com.synology:crypteia.nzbget
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nzbget-config
  storageClassName: ""
  volumeName: nzbget-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-plex-dev
  labels:
    type: downloads-plex-dev
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/volume1/plex-dev"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-plex-dev
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: downloads-plex-dev
  storageClassName: ""
  volumeName: downloads-plex-dev
---
