apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo/remote/
    repoURL: 'https://github.com/scuffe82/helios'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default