apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spenceops.com
  namespace: networking
spec:
  secretName: spenceops-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: spenceops.com
  dnsNames:
    - "spenceops.com"
    - "*.spenceops.com"