ingressClass:
  enabled: true
  isDefaultClass: false
  name: "traefik-external"

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    allowExternalNameServices: true
    ingressClass: "traefik-external"
  kubernetesIngress:
    allowExternalNameServices: true
    ingressClass:  "traefik-external"

  kubernetesGateway:
    enabled: false

ports:
  traefik:
    expose:
      default: true

service:
  spec:
   loadBalancerIP: "10.0.1.111"

additionalArguments:
  - "--serverstransport.insecureskipverify=true"