apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '21.0.3'
    chart: nginx
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true