apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urunner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: oci://ghcr.io/texano00/urunner/helm/urunner
    targetRevision: '0.6.5'
    path: /
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true




