apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo/helios/ops
    repoURL: 'https://github.com/scuffe/helios'
    targetRevision: HEAD
  project: default